<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addedProductName</name>
   <tag></tag>
   <elementGuidId>7afe6b2b-7615-4ae1-badf-6ff5e6af6cae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[data-ui-id=&quot;page-title-wrapper&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
