<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bagsHeading</name>
   <tag></tag>
   <elementGuidId>bfcf351f-5c5d-4c27-8476-0e4f438798fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[data-ui-id=&quot;page-title-wrapper&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>span[data-ui-id=&quot;page-title-wrapper&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
