<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>successMsg</name>
   <tag></tag>
   <elementGuidId>5b6c6db6-f040-4f60-a3a4-9cda3928f792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[data-ui-id=&quot;message-success&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
